- type: startingGear
  id: MobClippyGear
  equipment:
    head: ClothingHeadMailCarrier
    id: CourierIDCard

- type: startingGear
  id: MobClarpyGear
  equipment:
    head: ClothingHeadHatPirate
    id: PirateFirstMateNFIDCard

- type: startingGear
  id: MobCappyGear
  equipment:
    head: ClothingHeadHatNfsdSmallCampaign
    id: DeputyIDCard
    belt: ClothingBeltNfsdWebbing

# Adopted from space-wizards #26265 (Thank you, PolterTzi)
- type: startingGear
  id: MobKoboldGear
  equipment:
    head: ClothingHeadHatStrawHat
    ears: ClothingHeadsetService
    jumpsuit: ClothingUniformJumpsuitHawaiRed
    id: YipYipIDCard
